### ISSUE TITLE
After rc1 update Tenor app appears to misconfigure URL

### ISSUE THREAD

**Issue by luckenbach** [wreiske/Rocket.Chat.App-Tenor#3]
After upgraded to 1.0.0 rc-1 release of RC the tenor app produces 

![image](https://user-images.githubusercontent.com/533852/55894318-86ad7680-5b7f-11e9-9c71-1263562b7e59.png)

When I inspect this URL via the web client I see the link is 

https://<my.rocket.chat.url>/https://media.tenor.com/images/5c27d3271e589475178efbfbcd4534b7/tenor.gif

**Comment by wreiske** [comment]
@luckenbach thanks for the report. Investigating now, it's probably an issue with Rocket.Chat, not this app. I'll let you know what I find.

**Comment by wreiske** [comment]
@luckenbach Do you have anything set for your CDN prefix in the admin settings, under General?

![image](https://user-images.githubusercontent.com/6295044/55899308-74890380-5b92-11e9-9964-bf7138aecb7c.png)

**Comment by wreiske** [comment]
@d-gubert has submitted a [pull request](https://github.com/RocketChat/Rocket.Chat/pull/14086) to resolve this. 

Thanks, @luckenbach for the report!

**Comment by luckenbach** [comment]
Just for follow up on this; we do not have CDN prefix set for but the "Use CDN Prefix for all assets" is set to True.
